---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "24"
year: "2014"
contributor: 
- "Stefan Wiederkehr"
title: "Ein leichter Einstieg in die Geschichtswissenschaft. Rezension zu: Doina Oehlmann (2012): Erfolgreich recherchieren – Geschichte (= Erfolgreich recherchieren). Berlin ; Boston MA : De Gruyter Saur. IX, 131 S., ISBN 978-3-11-027112-6 (brosch.), 978-3-11-027130-0 (E-Book), 19,95 €."
urn: "urn:nbn:de:kobv:11-100215917"
date: 2014-03-05 20:50
comments: false
sharing: true
footer: true

---