---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "24"
year: "2014"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial LIBREAS #24: Zukünfte"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100215955"
date: 2014-03-05 20:50
comments: false
sharing: true
footer: true

---
