---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "24"
year: "2014"
contributor: 
- "Joachim Schöpfel"
title: "Rezension zu: L’avenir des bibliothèques: l’exemple des bibliothèques universitaires / Florence Roche et Frédéric Saby (Hg.). – Villeurbanne: Presses de l’enssib, 2013. – 224 Seiten. – ISBN 978-10-91281-13-3: 34 €"
urn: "urn:nbn:de:kobv:11-100215909"
date: 2014-03-05 20:50
comments: false
sharing: true
footer: true

---