---

layout: page
journal: "LIBREAS. Library Ideas"
issue: "24"
year: "2014"
contributor: 
- "Corinna Haas"
- "Beate Rusch"
title: "Piraten und Kapitalisten denken eine globale digitale Bibliothek. Eindrücke von der &bdquo;Complicity – Berliner Gazette Konferenz 2013&ldquo;"
subtitle: ""
abstract: "Wie können &bdquo;Piraten und &bdquo;Kapitalisten&ldquo; zusammenarbeiten? Welche Komplizenschaften können Hacker und Journalisten, Profis und Amateure miteinander eingehen, wenn es darum geht, die Informationsfreiheit im Internet zu verteidigen? Diesen Fragen ging die &bdquo;Complicity – Berliner Gazette Konferenz 2013&ldquo; im Berliner SUPERMARKT nach. Die Autorinnen kommentieren die Konferenz aus ihrer Perspektive als Teilnehmerinnen. Ihr Beitrag reflektiert die Konfrontation von Bibliotheksutopie und Bibliotheksrealität, den &bdquo;piratischen&bdquo; Umgang mit Urheberrechtsproblemen und Open Access sowie die Interessenkonvergenzen von Bibliothekaren und Internetaktivisten"
abstractalt: "How can pirates and capitalists work together? And how is it possible for hackers and journalists, professionals and amateurs to enter into complicity, in order to defend the freedom of information on the web? These were the issues the Complicity – Berliner Gazette Conference 2013&ldquo; dealt with at the SUPERMARKT in Berlin. The authors comment on the conference from a participant’s point of view. Their contribution reflects confrontations of utopias and realities of the library, &bdquo;pirate&bdquo; ways to deal with copyright problems and Open Access, as well as the convergence of interests between librarians and internet activists."
urn: ""
date: 2014-03-05 20:50
comments: false
sharing: true
footer: true

---