---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "24"
year: "2014"
contributor: 
- "Ulla Wimmer"
title: "Ein extrem praktisches Buch. Rezension zu: Doreen Siegfried, Sebastian Johannes Nix: Nutzerbezogene Marktforschung für Bibliotheken: eine Praxiseinführung. – Berlin: De Gruyter Saur, 2014"

urn: "urn:nbn:de:kobv:11-100215926"
date: 2014-03-05 20:50
comments: false
sharing: true
footer: true

---