---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "24"
year: "2014"
contributor: 
- "Wolfgang Kaiser"
title: "Auf in die Zukunft! Was kommt nach der bücherlosen Bibliothek? Reflexionen und Wahrnehmungsunterschiede zur Rolle von öffentlichen Bibliotheken"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100215931"
date: 2014-03-05 20:50
comments: false
sharing: true
footer: true

---
