---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "24"
year: "2014"
contributor: 
- "Eliane Blumer"
- "Karsten Schuldt"
title: "Diese Zukunft war einmal: Ehemals moderne Bibliotheken, heute"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100215863"
date: 2014-03-05 20:50
comments: false
sharing: true
footer: true

---
