---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "24"
year: "2014"
contributor: 
- "Rudolf Mumenthaler"
title: "Mit Expertenwissen zu Aussagen über künftige Entwicklungen &mdash; der Horizon Report Higher Education"
subtitle: ""
abstract: "Der Horizon Report Higher Education dient auch für Hochschulbibliotheken als wichtige Referenz zur Bewertung aktueller Trends und künftiger Entwicklungen. Der Autor stellt die dem Report zugrunde liegende Methode vor, beleuchtet diese kritisch und reflektiert die Aussagekraft der Prognosen. Die Stärken des Horizon Report liegen in der breiten Abstützung, der Offenheit des Verfahrens und der Publikation sowie der Ausarbeitung der von Expertinnen und Experten ausgewählten Themen. Gewisse Schwächen sieht der Autor in der Abhängigkeit von anderen Trendstudien sowie beim Auswahlverfahren der Trendthemen."
urn: "urn:nbn:de:kobv:11-100215886"
date: 2014-03-05 20:50
comments: false
sharing: true
footer: true

---
